const data = [
    {
        uri: "https://luehangs.site/pic-chat-app-images/animals-avian-beach-760984.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/animals-avian-beach-760984.jpg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/beautiful-blond-blonde-hair-478544.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/beautiful-blond-blonde-hair-478544.jpg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-women-beauty-40901.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-women-beauty-40901.jpg",
        id: "xbg72uclk",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/beautiful-blond-fishnet-stockings-48134.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/beautiful-blond-fishnet-stockings-48134.jpg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-woman-beauty-9763.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-woman-beauty-9763.jpg",
        id: idGenerator(),
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/attractive-balance-beautiful-186263.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/attractive-balance-beautiful-186263.jpg",
        title: "Lue Hang",
        // width: 1920,
        // height: 1080,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/pexels-photo-846741.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/pexels-photo-846741.jpeg",
        title: "Lue Hang",
        // width: 1920,
        // height: 1080,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/beautiful-daylight-dress-459947.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/beautiful-daylight-dress-459947.jpg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/pexels-photo-247292.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/pexels-photo-247292.jpeg",
        title: "Lue Hang",
        // width: 1920,
        // height: 1080,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/free-freedom-girl-6480.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/free-freedom-girl-6480.jpg",
        id: idGenerator(),
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/hair-girl-female-model.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/hair-girl-female-model.jpg",
        title: "Lue Hang",
        description: "https://luehangs.site",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/pexels-photo-853168.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/pexels-photo-853168.jpeg",
        title: "Lue Hang",
        // width: 1920,
        // height: 1080,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/pexels-photo-904276.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/pexels-photo-904276.jpeg",
        title: "Lue Hang",
        // width: 1920,
        // height: 1080,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/pexels-photo-1059116.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/pexels-photo-1059116.jpeg",
        id: idGenerator(),
        title: "Lue Hang",
        // width: 1920,
        // height: 1080,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/photo-206330.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/photo-206330.jpeg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/photo-206381.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/photo-206381.jpeg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/adult-arm-art-326559.jpg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/adult-arm-art-326559.jpg",
        title: "Lue Hang",
        // width: 1920,
        // height: 1080,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/photo-755745.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/photo-755745.jpeg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/pexels-photo-1104114.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/pexels-photo-1104114.jpeg",
        id: idGenerator(),
        title: "Lue Hang",
        // width: 1920,
        // height: 1080,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/photo-274595.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/photo-274595.jpeg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    },
    {
        uri: "https://luehangs.site/pic-chat-app-images/photo-799443.jpeg",
        thumbnail: "https://luehangs.site/pic-chat-app-images/photo-799443.jpeg",
        title: "Lue Hang",
        // width: 1080,
        // height: 1920,
    }
];

function idGenerator() {
    return Math.random().toString(36).substr(2, 9);
}

module.exports = data;
